user_agent = """Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:45.0) Gecko/20100101 Firefox/45.0"""

db {
	url = "jdbc:postgresql://172.28.3.13/test"
	username = "postgres"
	password ="asdf1234"
	driver = "org.postgresql.Driver"
}